version: "2"
services:
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - app
    networks:
      - app-network


  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://root:supersecret@mongo:27017/admin
      #- PORT=3000
    depends_on:
      - mongo
    networks:
      - app-network 

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=supersecret
      #- MONGODB_URL=localhost
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
